---
- name: Set up Apache on my webservers created using terraform
  hosts: all
  become: true
  tasks:

    - name: Update and upgrade apt repos and libraries on known hosts
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Apache on Hosts
      apt:
        name: apache2
        state: latest

    - name: Set timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos

    - name: Print Hostname on the screen
      tags: print
      shell: echo "<h1>My Hostname is $(hostname -f)</h1>" > /var/www/html/index.html
