---

- hosts: all
  become: yes
  tasks:

  - name: Update and upgrade apt repo and libraries on hosts
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install nginx on hosts
    apt: 
      name: nginx
      state: latest

  - name: Print hostname on screen
    tags: print
    shell: echo "<h1>The hostname of this server is $(hostname -f)</h1>" > /var/www/html/index.nginx-debian.html

  - name: Restart Nginx
    tags: restart
    service:
      name: nginx
      state: restarted
      enabled: yes
